name: Build image

on: 
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      image-name: "teste-build"

    steps:
      - name: Baixar arquivos
        uses: actions/checkout@v4

      - name: Build da imagem
        run: |
          docker image build -t ${{ env.image-name }}:${{ github.run_number }} .

      - name: Verificar imagens
        run: |
          docker image ls


      - name: Testes da função circunferencia
        run: |
          resultado=$(docker container run ${{ env.image-name }}:${{ github.run_number }} 2)
          echo "resultado=${resultado}"
          if [ ${resultado} != "12.56" ]; then
            exit 1
          fi

          resultado=$(docker container run ${{ env.image-name }}:${{ github.run_number }} 3)
          echo "resultado=${resultado}"
          if [ ${resultado} != "18.84" ]; then
            exit 1
          fi