name: Build image

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      image-name: "teste-build"

    steps:
      - name: Baixar arquivos
        uses: actions/checkout@v4

      - name: Build da imagem - manual
        run: |
          docker image build -t ${{ env.image-name }}:${{ github.run_number }}-manual .
          docker image ls

      - name: Build da imagem - action
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: ${{ env.image-name }}:${{ github.run_number }}-action

      - name: Teste env do step
        run: |
          echo "image-name=${{ env.image-name }}"