name: Build image

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      image-name: "teste-build"

    steps:
      - name: Baixar arquivos
        uses: actions/checkout@v4

      - name: Build da imagem
        run: |
          docker image build -t ${{ env.image-name }}:${{ github.run_number }} .
          docker image ls

      - name: Teste env do step
        run: |
          echo "image-name=${{ env.image-name }}"