name: Build image

on:
  push:
    branches:
      - 'main'
    paths:
      - 'Dockerfile'
      - '**.py'
      - '.github/**'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:3.11.10-alpine3.20 #docker:latest
      ports:
        - 80:80
      volumes:
        - volume:/volume_mount
    env:
      image-name: "teste-build"
      imagem-python: '3.11.10-alpine3.20'

    steps:
      - name: Versão docker
        run: docker version

      - name: Baixar arquivos
        uses: actions/checkout@v4

      - name: Alterar Dockerfile
        run: |
          cp Dockerfile Dockerfile-${{ env.imagem-python }}
          sed -i 's,IMAGEM_BASE,${{ env.imagem-python }},g' Dockerfile-${{ env.imagem-python }}
          cat Dockerfile-${{ env.imagem-python }}

      - name: Build da imagem
        run: |
          docker image build -t ${{ env.image-name }}:${{env.imagem-python}}-${{ github.run_number }} -f Dockerfile-${{ env.imagem-python }} .

      - name: Verificar imagens
        run: |
          docker image ls

      - name: Inspecionar imagem
        run: docker image inspect ${{ env.image-name }}:${{env.imagem-python}}-${{ github.run_number }}

      - name: Testes da função circunferencia
        run: |
          primeiro_valor="2"
          primeiro_resultado="12.56"
          echo "::group::Teste com Valor ${primeiro_valor}"
          resultado=$(docker container run ${{ env.image-name }}:${{env.imagem-python}}-${{ github.run_number }} ${primeiro_valor})

          if [ ${resultado} != ${primeiro_resultado} ]; then
            echo "::error::O resultado esperado era ${primeiro_resultado} e o resultado foi ${resultado}"
            exit 1
          fi
          echo "A verificação com o valor ${primeiro_valor} retornou o valor esperado de ${primeiro_resultado}"
          echo "::endgroup::"

          segundo_valor="3"
          segundo_resultado="18.84"
          echo "::group::Teste com Valor ${segundo_valor}"
          resultado=$(docker container run ${{ env.image-name }}:${{env.imagem-python}}-${{ github.run_number }} ${segundo_valor})

          if [ ${resultado} != ${segundo_resultado} ]; then
            echo "::error ::O resultado esperado era ${segundo_resultado} e o resultado foi ${resultado}"
            exit 1
          fi
          echo "A verificação com o valor ${segundo_valor} retornou o valor esperado de ${segundo_resultado}"
          echo "::endgroup::"

  teste-versao:
    runs-on: ubuntu-latest
    steps:
      - name: Versão docker
        run: docker version