name: Build image

on: 
  push:
    branches:
      - 'main'

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar arquivos
        uses: actions/checkout@v4

      - name: Testes no código
        run: |
          valor="4"
          resultado_esperado="25.12"
          echo "::group::Teste do código com o valor ${valor}"
          resultado=$(python3 app.py 4)

          if [ ${resultado} != ${resultado_esperado} ]; then
            echo "::error::O resultado esperado era ${resultado_esperado} e o resultado foi ${resultado}"
            exit 1
          fi
          echo "A verificação com o valor ${valor} retornou o valor esperado de ${resultado_esperado}"
          echo "::endgroup::"

  build:
    needs: testes
    runs-on: ubuntu-latest
    env:
      image-name: "teste-build"

    steps:
      - name: Baixar arquivos
        uses: actions/checkout@v4

      - name: Build da imagem
        run: |
          docker image build -t ${{ env.image-name }}:${{ github.run_number }} .

      - name: Verificar imagens
        run: |
          docker image ls

      - name: Testes da função circunferencia
        run: |
          primeiro_valor="2"
          primeiro_resultado="12.56"
          echo "::group::Teste com Valor ${primeiro_valor}"
          resultado=$(docker container run ${{ env.image-name }}:${{ github.run_number }} ${primeiro_valor})

          if [ ${resultado} != ${primeiro_resultado} ]; then
            echo "::error::O resultado esperado era ${primeiro_resultado} e o resultado foi ${resultado}"
            exit 1
          fi
          echo "A verificação com o valor ${primeiro_valor} retornou o valor esperado de ${primeiro_resultado}"
          echo "::endgroup::"

          segundo_valor="3"
          segundo_resultado="18.84"
          echo "::group::Teste com Valor ${segundo_valor}"
          resultado=$(docker container run ${{ env.image-name }}:${{ github.run_number }} 3)

          if [ ${resultado} != ${segundo_resultado} ]; then
            echo "::error ::O resultado esperado era ${segundo_resultado} e o resultado foi ${resultado}"
            exit 1
          fi
          echo "A verificação com o valor ${segundo_valor} retornou o valor esperado de ${segundo_resultado}"
          echo "::endgroup::"

  verificacao:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: verificar imagens docker
        run: |
          docker image ls
