name: Build image

on: 
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      image-name: "teste-build"

    steps:
      - name: Baixar arquivos
        uses: actions/checkout@v4

      - name: Build da imagem - manual
        run: |
          docker image build -t ${{ env.image-name }}:${{ github.run_number }}-manual .

      - name: Build da imagem - action
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: ${{ env.image-name }}:${{ github.run_number }}-action

      - name: Verificar imagens
        run: |
          docker image ls


      - name: teste
        run: |
          resultado=$(docker container run ${{ env.image-name }}:${{ github.run_number }}-manual 2)
          if [ ${resultado} != "12.56" ]; then
            exit 1
          fi

          resultado=$(docker container run ${{ env.image-name }}:${{ github.run_number }}-manual 3)
          if [ ${resultado} != "18.84" ]; then
            exit 1
          fi