name: Build image

on: 
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      image-name: "teste-build"

    steps:
      - name: Baixar arquivos
        uses: actions/checkout@v4

      - name: Build da imagem
        run: |
          docker image build -t ${{ env.image-name }}:${{ github.run_number }} .

      - name: Verificar imagens
        run: |
          docker image ls

      - name: Testes da função circunferencia
        run: |
          echo "::info ::Iniciando os testes"

          echo "::warning ::Esse é um warning"

          echo "::debug::Mensagem para ajudar a verificar algum problema"

          resultado=$(docker container run ${{ env.image-name }}:${{ github.run_number }} 2)

          if [ ${resultado} != "12.56" ]; then
            echo "::error ::O resultado esperado era 12.56 e o resultado foi ${resultado}"
            exit 1
          fi

          resultado=$(docker container run ${{ env.image-name }}:${{ github.run_number }} 3)

          if [ ${resultado} != "18.84" ]; then
            echo "::error ::O resultado esperado era 18.84 e o resultado foi ${resultado}"
            exit 1
          fi