name: Build image

on:
  push:
    branches:
      - 'main'
    paths:
      - 'Dockerfile'
      - '**.py'
      - '.github/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      image-name: "teste-build"
    strategy:
      matrix:
        runner: ['ubuntu-22.04', 'ubuntu-24.04']
        imagem-python: ['3.11.10-alpine3.20', '3.12.10-alpine3.20', '3.13.3-alpine3.20']

    steps:
      - name: Baixar arquivos
        uses: actions/checkout@v4

      - name: Alterar Dockerfile
        run: |
          cp Dockerfile Dockerfile-${{ matrix.imagem-python }}
          sed -i 's,IMAGEM_BASE,${{ matrix.imagem-python }},g' Dockerfile-${{ matrix.imagem-python }}
          cat Dockerfile-${{ matrix.imagem-python }}


      - name: Build da imagem
        run: |
          docker image build -t ${{ env.image-name }}:${{matrix.imagem-python}}-${{ github.run_number }} -f Dockerfile-${{ matrix.imagem-python }} .

      - name: Verificar imagens
        run: |
          docker image ls

      - name: Inspecionar imagem
        run: docker image inspect ${{ env.image-name }}:${{matrix.imagem-python}}-${{ github.run_number }}

      - name: Testes da função circunferencia
        run: |
          primeiro_valor="2"
          primeiro_resultado="12.56"
          echo "::group::Teste com Valor ${primeiro_valor}"
          resultado=$(docker container run ${{ env.image-name }}:${{matrix.imagem-python}}-${{ github.run_number }} ${primeiro_valor})

          if [ ${resultado} != ${primeiro_resultado} ]; then
            echo "::error::O resultado esperado era ${primeiro_resultado} e o resultado foi ${resultado}"
            exit 1
          fi
          echo "A verificação com o valor ${primeiro_valor} retornou o valor esperado de ${primeiro_resultado}"
          echo "::endgroup::"

          segundo_valor="3"
          segundo_resultado="18.84"
          echo "::group::Teste com Valor ${segundo_valor}"
          resultado=$(docker container run ${{ env.image-name }}:${{matrix.imagem-python}}-${{ github.run_number }} ${segundo_valor})

          if [ ${resultado} != ${segundo_resultado} ]; then
            echo "::error ::O resultado esperado era ${segundo_resultado} e o resultado foi ${resultado}"
            exit 1
          fi
          echo "A verificação com o valor ${segundo_valor} retornou o valor esperado de ${segundo_resultado}"
          echo "::endgroup::"