name: Teste curl

on:
  workflow_dispatch

jobs:
  teste:
    runs-on: ubuntu-latest
    container:
      image: alpine/curl
    services:
      pagina_web:
        image: httpd
        ports:
          - 8080:80

    steps:
      - name: Teste curl
        run: curl localhost:8080
