name: Teste curl

on:
  workflow_dispatch

jobs:
  teste:
    runs-on: ubuntu-latest
    container:
      image: alpine/curl
    services:
      pagina_web:
        image: httpd
        ports:
          - 80:80

    steps:
      - name: Teste curl
        run: curl pagina_web:80
