name: Testando

on:
  push:
    branches:
      - 'main'
    paths:
      - 'Dockerfile'
      - '**.py'
      - '.github/**'
  

jobs:
  testando123:
    runs-on: ubuntu-latest
    steps:
      - name: Versão docker
        run: docker version